# configurações legadas, configurações realizadas no curso
# porém na época o github ainda admitia autenticação https
# ou seja, com usuário e senha, mas hoje a autenticação
# é feita somente via ssh e ainda sem ser rsa sha-1
#spring.application.name=hr-config-server
#server.port=8888

# definindo qual branch no git o servidor de configurações 
# obterá as configurações dos microservices
#spring.cloud.config.server.git.default-label=master

# configurando url do repositório
#spring.cloud.config.server.git.uri=https://github.com/johnsousac/ms-course-configs

# configurando usuario e senha do repositório pois o mesmo
# está com visibilidade privativa, estamos definindo o usuario e senha
# por meio de variáveis de ambiente
#spring.cloud.config.server.git.username=${GITHUB_USER}
#spring.cloud.config.server.git.password=${GITHUB_PASS}

server:
  port: 8888
  
spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: git@github.com:johnsousac/ms-course-configs.git
          hostKey: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          hostKeyAlgorithm: ecdsa-sha2-nistp256
          ignoreLocalSshSettings: true
          privateKey: |
                        -----BEGIN EC PRIVATE KEY-----
                        MHcCAQEEICobqE0751kDKC4J0PVh7CDrFa8+LF5JM+7c5wbHYVZ9oAoGCCqGSM49
                        AwEHoUQDQgAED1kYn6pt0uVjn8mTc3IIeGb/cp/LyP1zuoVHf9QVkeHPSg/5NmQj
                        5U4B2Kmn1NVh/3l/KZq8ctFSsasMHMVivw==
                        -----END EC PRIVATE KEY-----